name: create-zips

on:
  push:
    branches:
      - main

jobs:
  create-zips:
    runs-on: ubuntu-latest
    container: jimmyneville/sms-automations-docker-image
    steps:
      - name: check-out-code
        uses: actions/checkout@v2

      - name: configure-aws-creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: install-and-deploy
        run: |
          $(git diff-tree --no-commit-id --name-only -r $(git rev-parse HEAD) -- '***.py')

